# Generated by Django 4.2.7 on 2025-12-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='customerBills',
        ),
        migrations.AlterModelTable(
            name='billitem',
            table='billItems',
        ),
    ]
