# Generated by Django 4.2.7 on 2025-12-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clothitem',
            new_name='clothItems_categor_7508ab_idx',
            old_name='inventory_c_categor_0f043c_idx',
        ),
        migrations.RenameIndex(
            model_name='clothitem',
            new_name='clothItems_sku_d9eec1_idx',
            old_name='inventory_c_sku_fecdb5_idx',
        ),
        migrations.AlterModelTable(
            name='clothitem',
            table='clothItems',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stockLevels',
        ),
    ]
